### PR TITLE
Feature py3k, initial support for atom on python 3

### PR DESCRIPTION
**Pull request by dwillmer**
Hey Chris, 

As discussed, here's initial support for python 3, runs fine on os x and gentoo (no ability to test Windows here :). Needs proper str/unicode consistency due to your custom PyStringMaker (didn't want to rip that out without checking), PySequenceMethods needs discussing, and i need to fix sortedmap, but the rest looks ok.

Cheers,
Dave

### CODE REVIEW

**Comment by danielballan** [comment]
What is the status of this issue and Python 3 compatibility? I can lend some company time to this effort.

**Comment by sccolbert** [comment]
All new work is being done on the 1.0.0-dev branch, which is almost complete, and already runs on both Python 2 and 3.

The last remaining big-ticket item is decided what to do about observable members for the 1.0 version. There is a discussion about that here (which has kind of fizzled out):
https://groups.google.com/forum/#!topic/enaml/9bRrHEwFh5I

In my  experience, observable members is a feature that is often misused and leads to a lot of anti-patterns. Lately, I've been preferring to take a more explicit approach where the author of a model explicit defines the observable interface through the use of explicitly managed signals. I find that better patterns emerge when the observable interface of an object is kept small and explicit. It also has the side benefit of allowing simple batch updates. 

This approach is used heavily in the PhoshporJS toolkit I've been building, which will serve as the rendering backend for Enaml 1.0: https://github.com/phosphorjs

I'm very active on Phosphor at the moment, and don't have much free time for Atom. If you'd like to start a real conversation about what it will take to finish the 1.0.0-dev branch, and you are comfortable with writing C++ and using the Python C-api, then I'd be happy guide on that.

**Comment by MatthieuDartiailh** [comment]
Hi, 

I don't have a lot of free time either but if you open some issues about what remains to be done with basic guidance I could try to tackle some (as others might do too). Keep up your amazing work I can't wait to work with the new versions of atom and enaml.

Cheers

**Comment by peterazmanov** [comment]
Made working Python 3.4 fork [peterazmanov/atom](https://github.com/peterazmanov/atom) based on @dwillmer commits to support my Python 3.4 enaml 0.9.8 fork, 'str/unicode consistency' requires revision )

**Pull request closed without merging**
